services:
  postgres:
    container_name: jap_pg
    image: postgres
    environment:
      POSTGRES_USER: 'jpapg'
      POSTGRES_PASSWORD: 'jpapg'
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - jpa-net
    restart: unless-stopped

  mysql:
    container_name: jpa_mysql
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'jpams'
      MYSQL_PASSWORD: 'jpams'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - msdata:/var/lib/mysql
    networks:
      - jpa-net
    restart: unless-stopped

volumes:
  pgdata:
  msdata:

networks:
  jpa-net:
    driver: bridge
